### ISSUE TITLE
Logic error in class.mailfetch.php

### ISSUE THREAD

**Issue by onurgoker** [RockefellerArchiveCenter/osTicket#85]
Hi everyone, 

In class.mailfetch.php I found this code block:

        $seen = false;
        if (($thread = ThreadEntry::lookupByEmailHeaders($vars, $seen))
                && ($message = $thread->postEmail($vars))) {
            if (!$message instanceof ThreadEntry)
                // Email has been processed previously
                return $message;
            $ticket = $message->getTicket();
        } elseif ($seen) {
            // Already processed, but for some reason (like rejection), no
            // thread item was created. Ignore the email
            return true;
        } elseif (($ticket=Ticket::create($vars, $errors, 'Email'))) {
            $message = $ticket->getLastMessage();
        } else {
            //Report success if the email was absolutely rejected.
            if(isset($errors['errno']) && $errors['errno'] == 403) {
                // Never process this email again!
                ThreadEntry::logEmailHeaders(0, $vars['mid']);
                return true;
            }

            // Log an error to the system logs
            $mailbox = Email::lookup($vars['emailId']);
            $ost->logError('Mail Processing Exception', sprintf(
                "Mailbox: %s\nError(s): %s",
                $mailbox->getEmail(),
                print_r($errors, true)
            ), false);

            // Indicate failure of mail processing
            return null;
        }

In first elseif condition, since the variable $seen is false, this code block will never work. Why is there an elseif condition like elseif($seen) in the code block above?

**Comment by onurgoker** [comment]
@kellishaver @protich @slm4996 @matmattia @yakatz I will be glad whenever you answer my question. Thank you.

**Comment by helrond** [comment]
@onurgoker I think you filed this on the wrong repo.
